name: uxarray_build
channels:
  - conda-forge
  - nodefaults
dependencies:
  - antimeridian
  - cartopy
  - dask
  - datashader
  - gmpy2
  - h5netcdf
  - hdf5
  - holoviews
  - matplotlib-base
  - matplotlib-inline
  - netcdf4
  - numba
  - numpy
  - pandas
  - pathlib
  - pre_commit
  - pyarrow
  - pytest
  - pip
  - pytest-cov
  - requests
  - scikit-learn
  - scipy
  - shapely
  - spatialpandas
  - xarray
  - pip:
    - git+https://github.com/airspeed-velocity/asv
    - pyfma
    - git+https://github.com/airspeed-velocity/asv
