name: uxarray_build
channels:
  - conda-forge
  - nodefaults
dependencies:
  - antimeridian
  - cartopy
  - dask
  - datashader
  - gmpy2
  - geoviews
  - h5netcdf
  - hdf5
  - healpix
  - holoviews
  - hvplot
  - matplotlib-base
  - matplotlib-inline
  - netcdf4
  - numba
  - numpy
  - pandas
  - pathlib
  - pre_commit
  - polars
  - pyarrow
  - pytest
  - pip
  - pytest-cov
  - requests
  - scikit-learn
  - scipy
  - shapely
  - spatialpandas
  - pooch
  - geopandas
  - xarray
  - asv
  - pip:
    - git+https://github.com/philipc2/pyfma.git # fix until https://github.com/nschloe/pyfma/pull/17 is merged
