name: uxarray_build
channels:
  - conda-forge
dependencies:
  - cartopy
  - dask
  - datashader
  - gmpy2
  - holoviews
  - matplotlib-base
  - matplotlib_inline
  - netcdf4
  - numba
  - numpy
  - pandas<2.1.0
  - pathlib
  - pre_commit
  - pyarrow
  - pytest
  - pytest-cov
  - requests
  - scikit-learn
  - scipy
  - shapely
  - spatialpandas
  - xarray
  - pip:
    - antimeridian
    - pyfma
