name: uxarray_build
channels:
  - conda-forge
dependencies:
  - dask
  - netcdf4
  - numba
  # pinning the numpy version for numba compatibility
  - numpy>=1.2, <1.22
  - pathlib
  - pre_commit
  - pytest
  - pytest-cov
  - scipy
  - xarray
  - zarr
